# railway.toml  ────────────────────────────────────────────
# 1) Sección BUILD  (dejamos que Railway use Nixpacks)
[build]
  # sin instrucciones extra

# 2) Sección DEPLOY
[deploy]
  # Comando que mantiene el contenedor vivo:
  startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn wingstore.wsgi:application --bind 0.0.0.0:${PORT}"

# ──────────────────────────────────────────────────────────
